name: Build and Test

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11'
        cache: 'pipenv'   # caching pipenv dependencies
    - name: Install pipenv and pipx
      run: |
        pip install pipenv && pip install pipx

    - name: Install global dependencies
      run: |
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install poetry

    - name: Install Dependencies
      run: pipenv install --dev --skip-lock

    - name: Run Makefile
      run: make check
